### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by miguel-souza** [Annasoares58/Employees-registration#4]
https://github.com/Annasoares58/Employees-registration/blob/958e84fc869b3d01d0f1a543c2264c73396802a6/src/entites/Employees.java#L21

Pode alterar para:

`return list.stream().filter(x -> x.getId() == id).findFirst().isPresent();`

Que já retorna se tem algum Employees ou não.

**Comment by Annasoares58** [comment]
Realmente, obrigada pela sugestão.
